class Chits {
  static final List<String> chitsList = [
    "A Drop Of Tears Shed For Swami Never Goes Waste",
    "Accept Things As They Come",
    "Admit Your Mistake",
    "Aim High Soar High",
    "All The Best Bangaru",
    "All Your Dreams Will Be Realised",
    "Always Be Careful",
    "Always Speak The Truth",
    "Anger Is The Worst Enemy",
    "As You Sow, So Shall You Reap",
    "Ask For The Strength To Love Me",
    "Attach Yourself To Me",
    "Be A Good Boy Today",
    "Be Active",
    "Be An Example To Others",
    "Be Bold And Courageous",
    "Be Content With What You Have",
    "Be Humble",
    "Be Mature… Bad Boy",
    "Be Optimistic",
    "Be Optimistic, Bangaru",
    "Be Organised",
    "Be Punctual",
    "Be Simple And Sincere",
    "Be Truthful To Yourself",
    "Bear All And Say Nothing",
    "Believe In Yourself And You Will Achieve Success In Every Task",
    "Believe In Yourself And You Will Achieve Success In Everything",
    "Bring Good Name To Your Parents And Me",
    "Chant 108 Gayatri Mantra",
    "Chant Hanuman Chalisa",
    "Chant Sai Gayatri",
    "Chant Suprabhatam Being Wide Awake",
    "Cheer Up Bangaru",
    "Cleanliness Is Next To Godliness",
    "Crying For Good Washes You And Makes You Clean",
    "Dedicate Every Act As An Offering To Me",
    "Delay Doesn't Mean Denial. So, Pray On",
    "Depend On Me Fully",
    "Discipline Is The Hallmark Of A Sai Student",
    "Do Good, See Good And Be Good",
    "Do Namasmaran",
    "Do Not Argue With Everyone",
    "Do Not Be Lazy",
    "Do Not Get Distracted",
    "Do Not Gossip",
    "Do Not Grumble",
    "Do Not Miss The Opportunity Given By Me",
    "Do Not Skip Food",
    "Do Your Best. Sai Will Do The Rest",
    "Don't Become A Slave Of Your Senses",
    "Don't Sleep After Lunch",
    "Don’t Be Over-confident Be Self-confident",
    "Don’t Become A Slave Of Your Senses",
    "Don’t Bunk Lunch",
    "Don’t Eat Junk Food",
    "Don’t Miss Dinner",
    "Don’t Miss Lunch",
    "Don’t Worry, If You Are Right",
    "Every Time You Converse With Me, I Listen To You",
    "Expect My Dream",
    "Faith Can Move Mountains",
    "First You Be. Then Teach Others. Believe This",
    "Food Is God",
    "Food Is God. Don’t Waste Food",
    "Forgive And Forget Others Faults",
    "Forgive And Forget Others' Faults",
    "Go & Study In The Library After Classes",
    "Go And Make Up With Whom You Fought",
    "Go For An Extra Round Of Jogging",
    "Good Boy Dunnapotha. Be Good",
    "Have Vibhuti. Everything Will Be Fine",
    "Help Someone Today",
    "Hold My Hands And I Will Lead You",
    "Hugs & Kisses From Sai Maa",
    "I Am By Your Side… Always Bangaru",
    "I Am Listening To You, Converse With Me",
    "I Am Satisfied With You",
    "I Am The Silent Listener To Every Conversation Of Yours",
    "I Am Very Proud Of You, Bangaru",
    "I Am Waiting For Your Good Morning. So, Attend Suprabhatam Regularly",
    "I Am Waiting For Your ‘Good Morning’. So Attend Suprabhatam",
    "I Am Watching You",
    "I Am Watching You Always",
    "I Am Your Best Friend",
    "I Am Your True Friend",
    "I Have A Plan For Your Life And That Is All You Need To Know",
    "I Have Chosen You Because I Know That You Are Worthy Of It",
    "I Have Chosen You Because You Are Worthy Of It",
    "I Have Given You Many Talents. Put Them To Use",
    "I Know, I Love, I Care. Then Why This Unhappiness?",
    "I Love You",
    "I Will Always Be There For You",
    "I Will Guard You Just As The Eyelid Protects The Eye",
    "It Is Nice To Be Important. But, It Is More Important To Be Nice",
    "Keep Mounam For An Hour",
    "Know Your Purpose. Pray To Sai",
    "Laziness Is Rust And Dust",
    "Laziness Is The Rust And Dust. Realisations Are Rest And Best",
    "Learn From Your Mistakes",
    "Leave All Your Worries To Me, I Shall Take Care",
    "Leave All Your Worries To Me.",
    "Less Luggage More Comfort",
    "Less Luggage, More Comfort, Makes The Journey A Pleasure",
    "Life Is A Mixture Of Sorrow And Happiness",
    "Listen To Your Conscience",
    "Love Seeks No Reward: Love Is Its Own Reward",
    "My Blessings And Love Are Always With You..",
    "My Dear Child, You Need A Little More Patience",
    "My Grace Will Always Protect You",
    "My Love For You Is That Of A Thousand Mothers",
    "Nothing Can Separate You From Me",
    "One Who Gets More, Much Is Expected From Him",
    "Pain Is An Interval Between Two Joys",
    "Past Is Past, Forget It",
    "Past Is Past. Pay Attention To Your Present",
    "Pleasure Is An Interval Between Two Pains",
    "Power In You Is Greater Than The Problem Ahead Of You",
    "Practice Ceiling On Desires",
    "Practice Makes A Man Perfect",
    "Practice What You Preach",
    "Prayers Can Move Mountains",
    "Rather Than Saying, Oh God, I Have A Big Problem. Say, Oh Problem, I Have A Big God",
    "Read Sai Literature",
    "Realise That I Am Your Heartbeat",
    "Reduce Your Ego",
    "Remember The Good That Others Have Done To You",
    "Respect All Your Elders",
    "Respect Your Parents And Elders",
    "Rest Assured, I Will Write Your Exam",
    "Sacrifice Your Wishes For Others",
    "Sai's Bangaru... Cheer Up",
    "Sai's Command Must Be Your Breath",
    "Save Time, Money And Energy",
    "See God In All",
    "Silence Is Golden",
    "Speak Softly And Sweetly",
    "Study Well During Study Hours",
    "Success Is Sweet But Its Secret Is Sweet",
    "Suffering Is Grace",
    "Swami Is Proud Of You",
    "Swami Knows Everything About You",
    "Take Care Of Yourself. I Need You",
    "Take Care Of Yourself. I Will Need You",
    "Take One Step. I Will Take A Hundred Towards You",
    "Talk Less And Work More",
    "Tell Me Your Worries. I Will Take Care",
    "Test Is My Taste",
    "The Duty Of A Student Is To Study",
    "The Joy That You Cause In The Heart Of God Is The Only Worthwhile Achievement",
    "The Strongest Man In The World Is The One Who Stands Alone",
    "The Will Of God Will Not Take You Where The Grace Of God Cannot Keep You",
    "The Will Of God Will Not Take You Where The Grace Of God Cannot Reach You",
    "There Is Nothing That You & I Cannot Do Together",
    "Think Before You Act. Offer It To Sai",
    "This Is Love From Your Sai Maa. Believe This.",
    "This Too Shall Pass",
    "To Err Is Human To Forgive Is Divine",
    "Watch Your Words, Actions, Thoughts, Character And Heart",
    "Whatever Happens, Is For Your Own Good",
    "Whatever Happens, It Is For Your Good",
    "When Prayers Go Up, Blessings Come Down",
    "Why Fear When I Am Here",
    "Why So Upset? Be Happy",
    "Why This Castor Oil Face? Always Be Happy",
    "Write A Letter To Me",
    "Yearn For Me, I Shall Come",
    "You Are Grown-up. Be Responsible",
    "You Are My Instrument",
    "You Are My Instrument In Use",
    "You Are My Loving Child",
    "You Are My Sweet Child, Bangaru",
    "You Are Right. Go Ahead And Face The Challenge",
    "You Have Gained More Than What You Have Lost",
    "You Have Gained More Than You Have Lost",
    "Your Actions In The Past Are The Reasons. Remember Sai Will Take Care",
    "Your Availability Is More Important To Me Than Your Ability",
    "Your Heart Is My Residence. Keep It Clean",
    "Your Parents Are Under My Protection",
  ];
}
